### ISSUE TITLE
Can I have an example using this with JS instead of coffee? :)

### ISSUE THREAD

**Issue by admc** [sebv/node-wd-sync#1]
Looks really cool! I wanna give it a try but from javascript land.

admc

**Comment by sebv** [comment]
Ok will write a README for pure javascript people.

In the meantime just copy/paste the example in this page: http://js2coffee.org/. (in the coffee2js tab).

Seb.

**Comment by sebv** [comment]
made doc and examples JavaScript friendly.

Seb.

**Comment by admc** [comment]
Thanks! Looks great.
