### ISSUE TITLE
.sleep throws an error - uses undefined `Fiber` variable

### ISSUE THREAD

**Issue by gustaff-weldon** [sebv/node-wd-sync#11]
`wdSync.sleep` throws `Fiber is undefined` error

https://github.com/sebv/node-wd-sync/blob/master/lib/wd-sync.coffee#L88

I have fixed this by using `fiber.constructor.yield()`
Another option is exporting Fiber from `make-sync` and using it, but that's not the best way.

**Comment by sebv** [comment]
Fixed, thx for reporting.
