### ISSUE TITLE
sessionid in chrome undefined

### ISSUE THREAD

**Issue by teameh** [sebv/node-wd-sync#19]
Hi Sebastian,

Thank you for developing this library!

I noticed that if one changed the `browserName` from `firefox` to `chrome` the session's id `webdriver.remote.sessionid` is undefined and I need the ID to report the status of the test back to Sauce Labs.

See: https://github.com/tiemevanveen/node-wd-sync/commit/de18dfdc9585f68410d9340f865c033dd2c3345c

**Comment by sebv** [comment]
I see it is a chrome+sauce issue.

I added safer client side `getSessionId` method.
https://github.com/sebv/node-wd-sync/commit/7e7acce61879f1bc21f5947c38b4115f20b025b8

I've just published version 1.0.5.

**Comment by teameh** [comment]
Thanks!
