### ISSUE TITLE
@getElementsByXXX

### ISSUE THREAD

**Issue by jnutter** [sebv/node-wd-sync#21]
I am still seeing this issue reported in https://github.com/sebv/node-wd-sync/issues/6 that the element in elements is not properly wrapped the same way. For instance if I console.log `@elementsByCssSelector('ul li')[0]` and `@elementByCssSelector('ul li')` the objects are different. In the element way, the object has the prototypes showing like toJSON, doubleclick, etc, while the element in elements just has value, and browser.

**Comment by sebv** [comment]
I for sure wasn't thinking straight when I replied with my async code in #6.

Fixed in 1.2.0, example [here](https://github.com/sebv/node-wd-sync/blob/master/examples/coffee/5-sub-elements.coffee)

**Comment by jnutter** [comment]
Awesome! Thanks for the quick turn-a-round.
