### ISSUE TITLE
wd-zombie required?

### ISSUE THREAD

**Issue by pamelafox-coursera** [sebv/node-wd-sync#3]
I did an npm install node, tried to run the sample test, and got an error about wd-zombie being undefined. Maybe wd-zombie needs to be in 'dependencies'?

**Comment by sebv** [comment]
It only install in dev mode, cause I see it as an optional package.

To use it as a library, you need to add the dependency in your own project, should be indicated in the doc.

I had great hopes on zombie, but I found it would only be worth for simple sites, with no complex javascript. If you are doing a webapp, it is not worth considering, just use standard webdriver for now.  

Am thinking to re-implement headless driver using phantomjs. It'll be more solid, but phantomjs api is harder to work with, so not sure when I will have time to do it.

**Comment by pamelafox-coursera** [comment]
Hmm. The steps I followed were:
npm install wd-sync
And then I copied the Javascript example from the readme and tried to run it. That's when I got the error about wd-zombie required, even though that example does not include it. I'm afraid I don't have the stack trace for that anymore, though.

I also tried using zombie before and was disappointed - it behaves too dissimilar to a browser - for example, a normal browser would always select the first option in a <select> if none was selected, but zombie would just report the selected as null .

I tried the ghostdriver project (https://github.com/detro/ghostdriver) but it's not quite done. Maybe you could contribute to that?

**Comment by sebv** [comment]
Yeah you right something missing in the code to make it optional. Weird, really thought I had done it. Will fix.

**Comment by sebv** [comment]
Should be fixed now.
