### ISSUE TITLE
Crashes on Windows 7 (even with 1-wd-simple.js)

### ISSUE THREAD

**Issue by snickell** [sebv/node-wd-sync#9]
sync() is called, but any references to browser (or this) from within sync() result in a crash. 

Console output:

```
C:\Users\Seth\node_modules\wd-sync\examples\js>node 1-wd-simple.js

(null):0
(null)
```

I strongly suspect the issue is with fibers on windows, and is probably a "WONTFIX", but reporting the issue anyway ;-)

**Comment by snickell** [comment]
If you modify sync() to do a console.log("Hello world") as the first line, you get:

```
C:\Users\Seth\node_modules\wd-sync\examples\js>node 1-wd-simple.js
Hello world

(null):0
(null)
```

**Comment by snickell** [comment]
I should mention that basic fibers examples seem to run ok on this system.

**Comment by sebv** [comment]
Not sure what is happening, I tried to run the fibers test suite under my windows 7/parallel and it crashes as well. I don't really have time to investigate more windows fibers issues.

**Comment by snickell** [comment]
Yeah, I wouldn't mess with windows either, I really appreciate you even trying out the test-suite. Maybe fibers will be fixed upstream at some point.

node-wd-sync is really helpful, thanks for writing this wrapper! Since I didn't need async at all for testing, my test code is much clearer and more "provable" in sync form, which IMO is really important for tests.
